# docker-compose.production.yml

version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: markeeee3/kittygram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/
  frontend:
    env_file: .env
    image: markeeee3/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: markeeee3/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media/
    depends_on:
      - backend
